### ISSUE TITLE
When creating project with more words name, underscores are added to join the words in app name.

### ISSUE THREAD

**Issue by matoushybl** [Brightify/ReactantCLI#1]

**Comment by TadeasKriz** [comment]
Isn't that a correct behavior?

**Comment by matoushybl** [comment]
It might be for project files etc. But I certainly don't want user to see `Projecty_McProjectFace` instead of `Projecty McProjectFace` as an app name.
<img width="94" alt="screen shot 2017-05-15 at 11 41 11" src="https://cloud.githubusercontent.com/assets/1637156/26051796/99cf2a3c-3963-11e7-89d1-16b240caaa92.png">

**Comment by MatyasKriz** [comment]
Addressed in PR #4.
