### ISSUE TITLE
Error with "reactant init"?

### ISSUE THREAD

**Issue by alzin** [Brightify/ReactantCLI#15]
Hey there, I am trying to use ReactantCLI to create a new project, and I got this error after Reactant has started installing the libraries from inside the Podfile!!! Is there any solution for this bug!!?

My current development machine is MacBook Pro with "macOS Big Sur" and Xcode version 12.4,

Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Analyzing dependencies
Pre-downloading: `TorchORM` from `https://github.com/SwiftKit/Torch.git`, branch `swift-pm`
Downloading dependencies
Installing Differentiator (3.1.0)
Installing Reactant (1.2.0)
Installing ReactantLiveUI (0.2.0)
Installing ReactantUI (0.2.0)
[!] /opt/local/bin/bash -c 
set -e
swift build

Fetching https://github.com/TadeasKriz/FileKit.git
Fetching https://github.com/kylef/PathKit.git
Fetching https://github.com/kylef/Spectre.git
Fetching https://github.com/JohnSundell/ShellOut.git
Fetching https://github.com/xcodeswift/xcproj.git
Fetching https://github.com/tadija/AEXML.git
Cloning https://github.com/tadija/AEXML.git
Resolving https://github.com/tadija/AEXML.git at 4.6.0
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.8.0
Cloning https://github.com/xcodeswift/xcproj.git
Resolving https://github.com/xcodeswift/xcproj.git at 2.0.0
Cloning https://github.com/JohnSundell/ShellOut.git
Resolving https://github.com/JohnSundell/ShellOut.git at 2.1.0
Cloning https://github.com/kylef/PathKit.git
Resolving https://github.com/kylef/PathKit.git at 0.9.0
[1/105] Compiling Tokenizer Assignable.swift
<unknown>:0: error: invalid value '3' in '-swift-version 3'
<unknown>:0: note: valid arguments to '-swift-version' are '4', '4.2', '5'
/Users/alzin_mohamad_ghaith/Library/Caches/CocoaPods/Pods/Release/ReactantUI/0.2.0-6d209/.build/checkouts/PathKit/Sources/PathKit.swift:98:14: warning: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'Path' to 'Hashable' by implementing 'hash(into:)' instead
  public var hashValue: Int {
             ^
/Users/alzin_mohamad_ghaith/Library/Caches/CocoaPods/Pods/Release/ReactantUI/0.2.0-6d209/.build/checkouts/PathKit/Sources/PathKit.swift:45:16: warning: 'substring(from:)' is deprecated: Please use String slicing subscript with a 'partial range from' operator.
      path = p.substring(from: p.characters.index(after: p.startIndex))
               ^
/Users/alzin_mohamad_ghaith/Library/Caches/CocoaPods/Pods/Release/ReactantUI/0.2.0-6d209/.build/checkouts/PathKit/Sources/PathKit.swift:45:34: error: 'characters' is unavailable: Please use String directly
      path = p.substring(from: p.characters.index(after: p.startIndex))
                                 ^~~~~~~~~~
Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
    public var characters: String { get set }
               ^
/Users/alzin_mohamad_ghaith/Library/Caches/CocoaPods/Pods/Release/ReactantUI/0.2.0-6d209/.build/checkouts/PathKit/Sources/PathKit.swift:601:32: warning: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value
      return (0..<Int(matchc)).flatMap { index in
                               ^
/Users/alzin_mohamad_ghaith/Library/Caches/CocoaPods/Pods/Release/ReactantUI/0.2.0-6d209/.build/checkouts/PathKit/Sources/PathKit.swift:601:32: note: use 'compactMap(_:)' instead
      return (0..<Int(matchc)).flatMap { index in
                               ^~~~~~~
                               compactMap

**Comment by TadeasKriz** [comment]
Thank you for your interest in Reactant. Unfortunately Reactant is no longer being actively developed and we'll be sunsetting it in the near future. Please consider using a different architecture and runtime. Thanks!
