### ISSUE TITLE
Generate Base.lproj

### ISSUE THREAD

**Issue by matoushybl** [Brightify/ReactantCLI#6]

**Comment by MatyasKriz** [comment]
What do we need this for? According to Apple:
> The Base.lproj folder contains all the .storyboard or .xib files in the development language. The folders for languages that you add to your project contain a strings file for each .storyboard or .xib file in your project. The development language folder doesn’t contain strings files for the .storyboard and .xib files because they don’t require translation in the development language. All the language folders contain a InfoPlist.strings file used to localize bundle properties, such as the app name. Any other localized resources—such as strings files that you generate and use from your code—appear in these language folders.

Doesn't Reactant ignore the .xib and .storyboard files? Or is it about the InfoPlist.strings file?

**Comment by TadeasKriz** [comment]
We still need the LaunchScreen.xib in Base.lproj.

**Comment by MatyasKriz** [comment]
Does this differ from project to project?
